from api.serializers.users_serializer import UsersSerializer
from api.serializers.project_sereializer import ProjectSerializer
from api.serializers.like_serializer import LikeSerializer
from api.serializers.user_tags_serializer import UserTagsSerializer
from api.serializers.course_tags_serializer import CourseTagsSerializer
from api.serializers.course_serializer import CourseSerializer
from api.serializers.comment_serializer import CommentSerializer